config/routes.rb
Rails.application.routes.draw do
  get'projects/index'
  #get 'projects/dashboard'
  post 'projects/new'
  get 'dashboard', to: 'projects#dashboard'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'projects#index'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true
  validates :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: [:dashboard]

  def index
    
  end

  def new
    @project = Project.create(name: params[:project][:name], description: params[:project][:description], start_date: params[:project][:start_date], end_date: params[:project][:end_date], content: params[:project][:content])
    
  end

  def dashboard
    if params[:content].present?
      @projects = Project.where(content: params[:content])
    else
      @projects = Project.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/dashboard.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
  <a class="navbar-brand mx-auto ">Dashboard de Proyectos</a>
  <form class="form-inline" name="dashboard">
    <%# <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="content"> %>
    <select class="form-control" id="content" name="content">
      <option></option>
      <option>Propuesta</option>
      <option>En progreso</option>
      <option>Terminado</option>
    </select>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Estado</button>
  </form>
</nav>
<%#<%= form_with url: projects_dashboard_path, method: :get do %>
<%#<%= select_tag("content", options_for_select(['Propuesta','En Progreso','Terminado']), include_blank: true) %>
<%#<%= submit_tag 'filtrar'%>
<%#<%end%>
<table class="table">
  <tr>
    <th>Nombre del Proyecto</th>
    <th>Descripción</th>
    <th>Fecha inicio </th>
    <th>Fecha término</th>
    <th>Estado</th>
  </tr>
  <% @projects.each do |project|%>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><%= project.start_date %></td>
      <td><%= project.end_date %></td>
      <td><%= project.content %></td>
    </tr>
  <% end %>

</table>

app/views/projects/index.html.erb
<h1>Ingresa un Proyecto</h1><hr><hr>

<%= form_for :project, url: projects_new_path do |f| %>
 
  <%= f.label(:name,'nombre')%>
	<%= f.text_field :name %>
  <%= f.label(:description, 'Descripción')%>
	<%= f.text_field :description %>
  <%= f.label(:start_date, 'Fecha Inicio')%>
  <%= f.date_field :start_date %>
  <%= f.label(:end_date,'Fecha Término') %>
  <%= f.date_field :end_date %>
  <%= f.label(:content,'Estado')%>
  <%= select(:project, :content,[['Propuesta'], ['En progreso'], ['Terminado']], include_blank: false)%>
	<%= f.submit 'Guardar' %>
<% end %>

app/views/projects/new.html.erb
 <% if @project.errors.any?%>
  <div id="error_explanation">
    <h2>
      <% pluralize(@project.errors.count, "error") %>
      Revisa nuevamente los siguientes campos:
    </h2>
    <ul>
      <% @project.errors.full_messages.each do |msg|%>
        <li><%= msg%></li>
      <% end %>
    </ul>
  </div>
<%else%>
 <h1>Proyecto Guardado con éxito</h1>
<%end%>
 <hr><button  onclick="history.back()" class="btn btn-primary btn-lg">Volver</button>